# Generated by Django 3.2.25 on 2025-06-29 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(help_text='Stock-keeping unit or other unique identifier', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Human-readable product name', max_length=120)),
                ('qty', models.PositiveIntegerField(default=0, verbose_name='Quantity on hand')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Auto-populated timestamp of last change')),
            ],
            options={
                'verbose_name': 'item',
                'verbose_name_plural': 'items',
                'ordering': ['sku'],
            },
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['sku'], name='inventory_i_sku_3e99d5_idx'),
        ),
    ]
